// Reading the logbook back. Most of these are about the ways a real
// ADIF file differs from the one we write: other programs' extension
// tags, four-digit times, values containing the bracket that a naive
// parser splits on, and a last record with no terminator.
// no-port-check: NereusSDR-original.

#include <QtTest/QtTest>
#include <QTemporaryDir>
#include <QTimeZone>

#include "core/AdifLog.h"

using namespace NereusSDR;

class TstAdifLog : public QObject {
    Q_OBJECT
private slots:
    void reads_a_record_we_wrote();
    void header_before_eoh_is_not_a_contact();
    void unknown_fields_are_ignored_not_fatal();
    void value_containing_a_bracket_survives();
    void four_digit_time_is_accepted();
    void last_record_without_eor_is_kept();
    void round_trip_preserves_the_fields();
    void missing_file_is_an_empty_log_not_an_error();
    void write_is_atomic_enough_to_replace();
    void csv_quotes_embedded_commas_and_quotes();
    void distance_is_recomputed_from_the_locators();

    void duplicate_within_tolerance_is_the_same_qso();
    void a_later_contact_with_the_same_station_is_not_a_duplicate();
    void a_different_band_or_mode_is_not_a_duplicate();
    void a_missing_band_does_not_make_it_a_different_contact();
    void submode_detail_does_not_split_a_contact();
    void merge_adds_only_what_is_new();
    void merge_never_replaces_an_existing_record();
    void merge_dedupes_within_the_incoming_file_too();

    void bands_sort_by_frequency_not_by_name();
    void centimetre_bands_sort_above_metre_bands();
    void unrecognised_bands_sort_together();
};

void TstAdifLog::reads_a_record_we_wrote()
{
    LogEntry e;
    e.call = QStringLiteral("OE1W");
    e.timeOn = QDateTime(QDate(2026, 8, 7), QTime(14, 5, 9), QTimeZone::UTC);
    e.band = QStringLiteral("40m");
    e.mode = QStringLiteral("SSB");
    e.submode = QStringLiteral("LSB");
    e.rstSent = QStringLiteral("59");

    const QVector<LogEntry> back =
        AdifLog::parse(e.toAdifRecord() + QStringLiteral("\n"));
    QCOMPARE(back.size(), 1);
    QCOMPARE(back.at(0).call, QStringLiteral("OE1W"));
    QCOMPARE(back.at(0).band, QStringLiteral("40m"));
    QCOMPARE(back.at(0).submode, QStringLiteral("LSB"));
    QCOMPARE(back.at(0).timeOn.toUTC(), e.timeOn);
}

void TstAdifLog::header_before_eoh_is_not_a_contact()
{
    // A header can legally contain fields. Counting them as a QSO would
    // put a phantom contact at the top of every log.
    const QString text = QStringLiteral(
        "Generated by something\n"
        "<ADIF_VER:5>3.1.4 <PROGRAMID:9>NereusSDR <EOH>\n"
        "<CALL:4>OE1W <EOR>\n");
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
}

void TstAdifLog::unknown_fields_are_ignored_not_fatal()
{
    const QString text = QStringLiteral(
        "<EOH>\n"
        "<CALL:4>OE1W <APP_LOG4OM_QSLSENT:1>Y <QSLMSG:5>Hello "
        "<BAND:3>40m <EOR>\n");
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
    QCOMPARE(v.at(0).band, QStringLiteral("40m"));
}

void TstAdifLog::value_containing_a_bracket_survives()
{
    // ADIF is length-prefixed precisely so this is legal. A parser that
    // split on '<' would truncate the comment and then mis-read every
    // field after it.
    const QString comment = QStringLiteral("ant <5m> vertical");
    const QString text = QStringLiteral("<EOH>\n<CALL:4>OE1W <COMMENT:%1>%2 "
                                        "<BAND:3>40m <EOR>\n")
                             .arg(comment.length()).arg(comment);
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).comment, comment);
    QCOMPARE(v.at(0).band, QStringLiteral("40m"));
}

void TstAdifLog::four_digit_time_is_accepted()
{
    // TIME_ON may be hhmm or hhmmss; loggers disagree.
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <QSO_DATE:8>20260807 <TIME_ON:4>1405 <EOR>\n"));
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).timeOn.toUTC().time(), QTime(14, 5));
}

void TstAdifLog::last_record_without_eor_is_kept()
{
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <BAND:3>40m <EOR>\n<CALL:5>DL1AB <BAND:3>20m\n"));
    QCOMPARE(v.size(), 2);
    QCOMPARE(v.at(1).call, QStringLiteral("DL1AB"));
}

void TstAdifLog::round_trip_preserves_the_fields()
{
    LogEntry a;
    a.call = QStringLiteral("VK3ABC");
    a.timeOn = QDateTime(QDate(2026, 1, 2), QTime(3, 4, 5), QTimeZone::UTC);
    a.band = QStringLiteral("20m");
    a.mode = QStringLiteral("CW");
    a.rstSent = QStringLiteral("599");
    a.rstRcvd = QStringLiteral("579");
    a.gridSquare = QStringLiteral("QF22");
    a.myGridSquare = QStringLiteral("JN67VV");
    a.name = QStringLiteral("Bruce");
    a.qth = QStringLiteral("Melbourne");
    a.country = QStringLiteral("Australia");
    a.comment = QStringLiteral("first VK, comma, and \"quotes\"");
    a.freqMHz = 14.025;

    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString path = dir.filePath(QStringLiteral("log.adi"));

    QString err;
    QVERIFY2(AdifLog::write(path, {a}, &err), qPrintable(err));

    const QVector<LogEntry> v = AdifLog::read(path, &err);
    QVERIFY2(err.isEmpty(), qPrintable(err));
    QCOMPARE(v.size(), 1);
    const LogEntry& b = v.at(0);
    QCOMPARE(b.call, a.call);
    QCOMPARE(b.timeOn.toUTC(), a.timeOn);
    QCOMPARE(b.band, a.band);
    QCOMPARE(b.mode, a.mode);
    QCOMPARE(b.rstSent, a.rstSent);
    QCOMPARE(b.rstRcvd, a.rstRcvd);
    QCOMPARE(b.gridSquare, a.gridSquare);
    QCOMPARE(b.myGridSquare, a.myGridSquare);
    QCOMPARE(b.name, a.name);
    QCOMPARE(b.qth, a.qth);
    QCOMPARE(b.country, a.country);
    QCOMPARE(b.comment, a.comment);
    QVERIFY(std::abs(b.freqMHz - a.freqMHz) < 1e-6);
}

void TstAdifLog::missing_file_is_an_empty_log_not_an_error()
{
    // A new installation has no file. Reporting that as a failure would
    // put a warning box in front of someone on their first QSO.
    QTemporaryDir dir;
    QString err = QStringLiteral("untouched");
    const QVector<LogEntry> v =
        AdifLog::read(dir.filePath(QStringLiteral("nope.adi")), &err);
    QVERIFY(v.isEmpty());
    QCOMPARE(err, QStringLiteral("untouched"));
}

void TstAdifLog::write_is_atomic_enough_to_replace()
{
    QTemporaryDir dir;
    const QString path = dir.filePath(QStringLiteral("log.adi"));

    LogEntry a; a.call = QStringLiteral("OE1W");
    LogEntry b; b.call = QStringLiteral("DL1AB");
    QVERIFY(AdifLog::write(path, {a, b}, nullptr));
    QCOMPARE(AdifLog::read(path).size(), 2);

    // Rewriting with one fewer must leave exactly one, not append.
    QVERIFY(AdifLog::write(path, {a}, nullptr));
    const QVector<LogEntry> v = AdifLog::read(path);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
}

void TstAdifLog::csv_quotes_embedded_commas_and_quotes()
{
    LogEntry e;
    e.call = QStringLiteral("OE1W");
    e.comment = QStringLiteral("loud, clear, said \"hi\"");
    const QString csv = AdifLog::toCsv({e});
    // RFC 4180: inner quotes doubled, whole value wrapped.
    QVERIFY(csv.contains(QStringLiteral("\"loud, clear, said \"\"hi\"\"\"")));
    // Header plus one row.
    QCOMPARE(csv.count(QLatin1Char('\n')), 2);
}

void TstAdifLog::distance_is_recomputed_from_the_locators()
{
    // ADIF has no distance field, so it has to come back from the two
    // locators or the logbook column would always be blank.
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <MY_GRIDSQUARE:6>JN67VV "
        "<GRIDSQUARE:6>FN30IV <EOR>\n"));
    QCOMPARE(v.size(), 1);
    QVERIFY2(v.at(0).distanceKm > 6500 && v.at(0).distanceKm < 7200,
             qPrintable(QStringLiteral("%1 km").arg(v.at(0).distanceKm)));
    QVERIFY2(v.at(0).bearingDeg > 280 && v.at(0).bearingDeg < 315,
             qPrintable(QStringLiteral("%1 deg").arg(v.at(0).bearingDeg)));
}

namespace {

LogEntry qso(const QString& call, const QString& band, const QString& mode,
             const QDateTime& when)
{
    LogEntry e;
    e.call = call;
    e.band = band;
    e.mode = mode;
    e.timeOn = when;
    return e;
}

QDateTime at(int h, int m, int s = 0)
{
    return QDateTime(QDate(2026, 8, 7), QTime(h, m, s), QTimeZone::UTC);
}

} // namespace

void TstAdifLog::duplicate_within_tolerance_is_the_same_qso()
{
    // The two ends of a contact log it seconds or a minute apart, and
    // clocks disagree. Re-importing from a friend's log or from LoTW
    // must not double the contact up.
    const LogEntry a = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                           QStringLiteral("SSB"), at(14, 0, 0));
    QVERIFY(AdifLog::isSameQso(a, a));
    QVERIFY(AdifLog::isSameQso(a, qso(QStringLiteral("oe1w"),
                                      QStringLiteral("40M"),
                                      QStringLiteral("ssb"), at(14, 0, 45))));
    QVERIFY(AdifLog::isSameQso(a, qso(QStringLiteral("OE1W"),
                                      QStringLiteral("40m"),
                                      QStringLiteral("SSB"), at(13, 58, 30))));
}

void TstAdifLog::a_later_contact_with_the_same_station_is_not_a_duplicate()
{
    // On a contest weekend the same station on the same band ten minutes
    // later is very often a genuine second contact. Merging those would
    // destroy data that cannot be recovered, which is why the window is
    // two minutes and not ten.
    const LogEntry a = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                           QStringLiteral("SSB"), at(14, 0));
    QVERIFY(!AdifLog::isSameQso(a, qso(QStringLiteral("OE1W"),
                                       QStringLiteral("40m"),
                                       QStringLiteral("SSB"), at(14, 10))));
    QVERIFY(!AdifLog::isSameQso(a, qso(QStringLiteral("OE1W"),
                                       QStringLiteral("40m"),
                                       QStringLiteral("SSB"), at(14, 2, 30))));
}

void TstAdifLog::a_different_band_or_mode_is_not_a_duplicate()
{
    const LogEntry a = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                           QStringLiteral("SSB"), at(14, 0));
    QVERIFY(!AdifLog::isSameQso(a, qso(QStringLiteral("OE1W"),
                                       QStringLiteral("20m"),
                                       QStringLiteral("SSB"), at(14, 0))));
    QVERIFY(!AdifLog::isSameQso(a, qso(QStringLiteral("OE1W"),
                                       QStringLiteral("40m"),
                                       QStringLiteral("CW"), at(14, 0))));
    QVERIFY(!AdifLog::isSameQso(a, qso(QStringLiteral("DL1AB"),
                                       QStringLiteral("40m"),
                                       QStringLiteral("SSB"), at(14, 0))));
}

void TstAdifLog::a_missing_band_does_not_make_it_a_different_contact()
{
    // An export that omitted BAND is not thereby a different QSO.
    // Treating it as one would import the whole file a second time.
    const LogEntry a = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                           QStringLiteral("SSB"), at(14, 0));
    const LogEntry b = qso(QStringLiteral("OE1W"), QString{},
                           QStringLiteral("SSB"), at(14, 0));
    QVERIFY(AdifLog::isSameQso(a, b));
    QVERIFY(AdifLog::isSameQso(b, a));
}

void TstAdifLog::submode_detail_does_not_split_a_contact()
{
    LogEntry a = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                     QStringLiteral("SSB"), at(14, 0));
    LogEntry b = a;
    b.submode = QStringLiteral("LSB");
    // One side spelling the same contact with more detail is still one
    // contact.
    QVERIFY(AdifLog::isSameQso(a, b));
}

void TstAdifLog::merge_adds_only_what_is_new()
{
    const QVector<LogEntry> mine = {
        qso(QStringLiteral("OE1W"),  QStringLiteral("40m"),
            QStringLiteral("SSB"), at(14, 0)),
        qso(QStringLiteral("DL1AB"), QStringLiteral("20m"),
            QStringLiteral("CW"),  at(15, 0)),
    };
    const QVector<LogEntry> theirs = {
        qso(QStringLiteral("OE1W"),  QStringLiteral("40m"),
            QStringLiteral("SSB"), at(14, 0, 30)),   // same
        qso(QStringLiteral("G3XYZ"), QStringLiteral("20m"),
            QStringLiteral("CW"),  at(16, 0)),       // new
    };

    const auto r = AdifLog::merge(mine, theirs);
    QCOMPARE(r.added, 1);
    QCOMPARE(r.skipped, 1);
    QCOMPARE(r.merged.size(), 3);
    QCOMPARE(r.merged.at(2).call, QStringLiteral("G3XYZ"));
}

void TstAdifLog::merge_never_replaces_an_existing_record()
{
    // The local log is the one that has been corrected by hand. An
    // import overwriting those corrections would be silent damage.
    LogEntry mineOne = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                           QStringLiteral("SSB"), at(14, 0));
    mineOne.comment = QStringLiteral("corrected by hand");
    mineOne.name    = QStringLiteral("Hans");

    LogEntry theirOne = qso(QStringLiteral("OE1W"), QStringLiteral("40m"),
                            QStringLiteral("SSB"), at(14, 0, 20));
    theirOne.comment = QStringLiteral("from the other end");
    theirOne.name    = QStringLiteral("WRONG");

    const auto r = AdifLog::merge({mineOne}, {theirOne});
    QCOMPARE(r.added, 0);
    QCOMPARE(r.merged.size(), 1);
    QCOMPARE(r.merged.at(0).comment, QStringLiteral("corrected by hand"));
    QCOMPARE(r.merged.at(0).name, QStringLiteral("Hans"));
}

void TstAdifLog::merge_dedupes_within_the_incoming_file_too()
{
    // A file that repeats a contact must not add it twice, which means
    // each accepted record has to join the pool the rest are checked
    // against.
    const LogEntry one = qso(QStringLiteral("G3XYZ"), QStringLiteral("20m"),
                             QStringLiteral("CW"), at(16, 0));
    const auto r = AdifLog::merge({}, {one, one, one});
    QCOMPARE(r.added, 1);
    QCOMPARE(r.skipped, 2);
    QCOMPARE(r.merged.size(), 1);
}

void TstAdifLog::bands_sort_by_frequency_not_by_name()
{
    // The trap this function exists for: as text, "160m" sorts before
    // "40m" because '1' precedes '4', and a logbook sorted by band then
    // lists 10m, 160m, 17m, 20m — wrong in a way that looks plausible
    // enough that nobody checks it.
    QStringList bands = {QStringLiteral("10m"), QStringLiteral("160m"),
                         QStringLiteral("20m"), QStringLiteral("40m"),
                         QStringLiteral("80m"), QStringLiteral("6m")};
    std::sort(bands.begin(), bands.end(),
              [](const QString& a, const QString& b) {
        return AdifLog::bandSortKeyMHz(a) < AdifLog::bandSortKeyMHz(b);
    });
    QCOMPARE(bands, QStringList({QStringLiteral("160m"), QStringLiteral("80m"),
                                 QStringLiteral("40m"), QStringLiteral("20m"),
                                 QStringLiteral("10m"), QStringLiteral("6m")}));

    // And the plain fact underneath it.
    QVERIFY(AdifLog::bandSortKeyMHz(QStringLiteral("160m"))
            < AdifLog::bandSortKeyMHz(QStringLiteral("40m")));
}

void TstAdifLog::centimetre_bands_sort_above_metre_bands()
{
    // 70cm is higher in frequency than 2m. Reading the number alone
    // would put it below everything.
    QVERIFY(AdifLog::bandSortKeyMHz(QStringLiteral("70cm"))
            > AdifLog::bandSortKeyMHz(QStringLiteral("2m")));
    QVERIFY(AdifLog::bandSortKeyMHz(QStringLiteral("23cm"))
            > AdifLog::bandSortKeyMHz(QStringLiteral("70cm")));
    // Roughly right, not just ordered: 70cm is around 430 MHz.
    const double k = AdifLog::bandSortKeyMHz(QStringLiteral("70cm"));
    QVERIFY2(k > 400.0 && k < 450.0, qPrintable(QString::number(k)));
    // Case and whitespace are not a different band.
    QCOMPARE(AdifLog::bandSortKeyMHz(QStringLiteral(" 40M ")),
             AdifLog::bandSortKeyMHz(QStringLiteral("40m")));
}

void TstAdifLog::unrecognised_bands_sort_together()
{
    // Blank and junk both give zero, so they gather at one end instead
    // of scattering through the list at whatever their text implies.
    QCOMPARE(AdifLog::bandSortKeyMHz(QString{}), 0.0);
    QCOMPARE(AdifLog::bandSortKeyMHz(QStringLiteral("  ")), 0.0);
    QCOMPARE(AdifLog::bandSortKeyMHz(QStringLiteral("banana")), 0.0);
    QCOMPARE(AdifLog::bandSortKeyMHz(QStringLiteral("40")), 0.0);   // no unit
    QCOMPARE(AdifLog::bandSortKeyMHz(QStringLiteral("0m")), 0.0);   // no divide
}

QTEST_APPLESS_MAIN(TstAdifLog)
#include "tst_adif_log.moc"
