// Reading the logbook back. Most of these are about the ways a real
// ADIF file differs from the one we write: other programs' extension
// tags, four-digit times, values containing the bracket that a naive
// parser splits on, and a last record with no terminator.
// no-port-check: NereusSDR-original.

#include <QtTest/QtTest>
#include <QTemporaryDir>
#include <QTimeZone>

#include "core/AdifLog.h"

using namespace NereusSDR;

class TstAdifLog : public QObject {
    Q_OBJECT
private slots:
    void reads_a_record_we_wrote();
    void header_before_eoh_is_not_a_contact();
    void unknown_fields_are_ignored_not_fatal();
    void value_containing_a_bracket_survives();
    void four_digit_time_is_accepted();
    void last_record_without_eor_is_kept();
    void round_trip_preserves_the_fields();
    void missing_file_is_an_empty_log_not_an_error();
    void write_is_atomic_enough_to_replace();
    void csv_quotes_embedded_commas_and_quotes();
    void distance_is_recomputed_from_the_locators();
};

void TstAdifLog::reads_a_record_we_wrote()
{
    LogEntry e;
    e.call = QStringLiteral("OE1W");
    e.timeOn = QDateTime(QDate(2026, 8, 7), QTime(14, 5, 9), QTimeZone::UTC);
    e.band = QStringLiteral("40m");
    e.mode = QStringLiteral("SSB");
    e.submode = QStringLiteral("LSB");
    e.rstSent = QStringLiteral("59");

    const QVector<LogEntry> back =
        AdifLog::parse(e.toAdifRecord() + QStringLiteral("\n"));
    QCOMPARE(back.size(), 1);
    QCOMPARE(back.at(0).call, QStringLiteral("OE1W"));
    QCOMPARE(back.at(0).band, QStringLiteral("40m"));
    QCOMPARE(back.at(0).submode, QStringLiteral("LSB"));
    QCOMPARE(back.at(0).timeOn.toUTC(), e.timeOn);
}

void TstAdifLog::header_before_eoh_is_not_a_contact()
{
    // A header can legally contain fields. Counting them as a QSO would
    // put a phantom contact at the top of every log.
    const QString text = QStringLiteral(
        "Generated by something\n"
        "<ADIF_VER:5>3.1.4 <PROGRAMID:9>NereusSDR <EOH>\n"
        "<CALL:4>OE1W <EOR>\n");
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
}

void TstAdifLog::unknown_fields_are_ignored_not_fatal()
{
    const QString text = QStringLiteral(
        "<EOH>\n"
        "<CALL:4>OE1W <APP_LOG4OM_QSLSENT:1>Y <QSLMSG:5>Hello "
        "<BAND:3>40m <EOR>\n");
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
    QCOMPARE(v.at(0).band, QStringLiteral("40m"));
}

void TstAdifLog::value_containing_a_bracket_survives()
{
    // ADIF is length-prefixed precisely so this is legal. A parser that
    // split on '<' would truncate the comment and then mis-read every
    // field after it.
    const QString comment = QStringLiteral("ant <5m> vertical");
    const QString text = QStringLiteral("<EOH>\n<CALL:4>OE1W <COMMENT:%1>%2 "
                                        "<BAND:3>40m <EOR>\n")
                             .arg(comment.length()).arg(comment);
    const QVector<LogEntry> v = AdifLog::parse(text);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).comment, comment);
    QCOMPARE(v.at(0).band, QStringLiteral("40m"));
}

void TstAdifLog::four_digit_time_is_accepted()
{
    // TIME_ON may be hhmm or hhmmss; loggers disagree.
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <QSO_DATE:8>20260807 <TIME_ON:4>1405 <EOR>\n"));
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).timeOn.toUTC().time(), QTime(14, 5));
}

void TstAdifLog::last_record_without_eor_is_kept()
{
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <BAND:3>40m <EOR>\n<CALL:5>DL1AB <BAND:3>20m\n"));
    QCOMPARE(v.size(), 2);
    QCOMPARE(v.at(1).call, QStringLiteral("DL1AB"));
}

void TstAdifLog::round_trip_preserves_the_fields()
{
    LogEntry a;
    a.call = QStringLiteral("VK3ABC");
    a.timeOn = QDateTime(QDate(2026, 1, 2), QTime(3, 4, 5), QTimeZone::UTC);
    a.band = QStringLiteral("20m");
    a.mode = QStringLiteral("CW");
    a.rstSent = QStringLiteral("599");
    a.rstRcvd = QStringLiteral("579");
    a.gridSquare = QStringLiteral("QF22");
    a.myGridSquare = QStringLiteral("JN67VV");
    a.name = QStringLiteral("Bruce");
    a.qth = QStringLiteral("Melbourne");
    a.country = QStringLiteral("Australia");
    a.comment = QStringLiteral("first VK, comma, and \"quotes\"");
    a.freqMHz = 14.025;

    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString path = dir.filePath(QStringLiteral("log.adi"));

    QString err;
    QVERIFY2(AdifLog::write(path, {a}, &err), qPrintable(err));

    const QVector<LogEntry> v = AdifLog::read(path, &err);
    QVERIFY2(err.isEmpty(), qPrintable(err));
    QCOMPARE(v.size(), 1);
    const LogEntry& b = v.at(0);
    QCOMPARE(b.call, a.call);
    QCOMPARE(b.timeOn.toUTC(), a.timeOn);
    QCOMPARE(b.band, a.band);
    QCOMPARE(b.mode, a.mode);
    QCOMPARE(b.rstSent, a.rstSent);
    QCOMPARE(b.rstRcvd, a.rstRcvd);
    QCOMPARE(b.gridSquare, a.gridSquare);
    QCOMPARE(b.myGridSquare, a.myGridSquare);
    QCOMPARE(b.name, a.name);
    QCOMPARE(b.qth, a.qth);
    QCOMPARE(b.country, a.country);
    QCOMPARE(b.comment, a.comment);
    QVERIFY(std::abs(b.freqMHz - a.freqMHz) < 1e-6);
}

void TstAdifLog::missing_file_is_an_empty_log_not_an_error()
{
    // A new installation has no file. Reporting that as a failure would
    // put a warning box in front of someone on their first QSO.
    QTemporaryDir dir;
    QString err = QStringLiteral("untouched");
    const QVector<LogEntry> v =
        AdifLog::read(dir.filePath(QStringLiteral("nope.adi")), &err);
    QVERIFY(v.isEmpty());
    QCOMPARE(err, QStringLiteral("untouched"));
}

void TstAdifLog::write_is_atomic_enough_to_replace()
{
    QTemporaryDir dir;
    const QString path = dir.filePath(QStringLiteral("log.adi"));

    LogEntry a; a.call = QStringLiteral("OE1W");
    LogEntry b; b.call = QStringLiteral("DL1AB");
    QVERIFY(AdifLog::write(path, {a, b}, nullptr));
    QCOMPARE(AdifLog::read(path).size(), 2);

    // Rewriting with one fewer must leave exactly one, not append.
    QVERIFY(AdifLog::write(path, {a}, nullptr));
    const QVector<LogEntry> v = AdifLog::read(path);
    QCOMPARE(v.size(), 1);
    QCOMPARE(v.at(0).call, QStringLiteral("OE1W"));
}

void TstAdifLog::csv_quotes_embedded_commas_and_quotes()
{
    LogEntry e;
    e.call = QStringLiteral("OE1W");
    e.comment = QStringLiteral("loud, clear, said \"hi\"");
    const QString csv = AdifLog::toCsv({e});
    // RFC 4180: inner quotes doubled, whole value wrapped.
    QVERIFY(csv.contains(QStringLiteral("\"loud, clear, said \"\"hi\"\"\"")));
    // Header plus one row.
    QCOMPARE(csv.count(QLatin1Char('\n')), 2);
}

void TstAdifLog::distance_is_recomputed_from_the_locators()
{
    // ADIF has no distance field, so it has to come back from the two
    // locators or the logbook column would always be blank.
    const QVector<LogEntry> v = AdifLog::parse(QStringLiteral(
        "<EOH>\n<CALL:4>OE1W <MY_GRIDSQUARE:6>JN67VV "
        "<GRIDSQUARE:6>FN30IV <EOR>\n"));
    QCOMPARE(v.size(), 1);
    QVERIFY2(v.at(0).distanceKm > 6500 && v.at(0).distanceKm < 7200,
             qPrintable(QStringLiteral("%1 km").arg(v.at(0).distanceKm)));
    QVERIFY2(v.at(0).bearingDeg > 280 && v.at(0).bearingDeg < 315,
             qPrintable(QStringLiteral("%1 deg").arg(v.at(0).bearingDeg)));
}

QTEST_APPLESS_MAIN(TstAdifLog)
#include "tst_adif_log.moc"
