# --------------------------------------------------------------------------
# LongpathBuildTag.cmake : derive the smoke-build tag and stamp it into a header
# --------------------------------------------------------------------------
# Run in script mode (cmake -P). It is invoked twice: once while configuring,
# so the generated header exists before the first compile, and once per build
# from the nereus_build_tag target, so the tag names the commit that is
# actually being compiled.
#
# Why the derivation moved out of configure (2026-08-01, KG4VCF): the tag used
# to be computed by execute_process while configuring and baked in as a
# compile definition, so it only refreshed when something else happened to
# force a re-configure. A build tree could sit five commits behind and keep
# printing the old sha in the title bar. That is worse than printing nothing:
# it names the wrong binary with total confidence, which is the exact mistake
# the stamp exists to prevent.
#
# Inputs, all passed with -D:
#   NEREUS_SOURCE_DIR      repository to interrogate
#   NEREUS_OUTPUT          header file to write
#   NEREUS_OVERRIDE        current value of the NEREUSSDR_BUILD_TAG cache var
#   NEREUS_GIT_EXECUTABLE  git, resolved once at configure time; may be empty
#   NEREUS_ANNOUNCE        ON to print the one-line status message
#
# The header is rewritten only when the tag actually changes, so a no-op
# rebuild stays a no-op: the script runs, finds the same text, and touches
# nothing, and no translation unit recompiles.

cmake_minimum_required(VERSION 3.16)

# An explicit NEREUSSDR_BUILD_TAG wins outright, matching the cache variable's
# documented contract: empty means "derive from git", any non-blank value is
# used verbatim, and a single space forces the tag off.
set(_tag "${NEREUS_OVERRIDE}")

if(NOT _tag AND NEREUS_GIT_EXECUTABLE)
    # Release gate. release.yml checks out `ref: <tag>`, so HEAD sits exactly
    # on a tag there and nowhere else. Release artifacts keep the clean
    # "NereusSDR 0.5.2" title and get no tag, dirty tree or not: a release
    # build must never acquire a suffix just because a workflow step touched
    # a tracked file before the compile.
    execute_process(
        COMMAND "${NEREUS_GIT_EXECUTABLE}" describe --exact-match --tags HEAD
        WORKING_DIRECTORY "${NEREUS_SOURCE_DIR}"
        RESULT_VARIABLE _head_is_tagged
        OUTPUT_QUIET ERROR_QUIET)

    if(NOT _head_is_tagged EQUAL 0)
        execute_process(
            COMMAND "${NEREUS_GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
            WORKING_DIRECTORY "${NEREUS_SOURCE_DIR}"
            OUTPUT_VARIABLE _branch
            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        execute_process(
            COMMAND "${NEREUS_GIT_EXECUTABLE}" rev-parse --short HEAD
            WORKING_DIRECTORY "${NEREUS_SOURCE_DIR}"
            OUTPUT_VARIABLE _sha
            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)

        # rev-parse --abbrev-ref prints the literal string HEAD on a detached
        # head, which would read as a branch named HEAD in the title bar.
        if(_branch STREQUAL "HEAD")
            set(_branch "detached")
        endif()

        if(_branch AND _sha)
            set(_tag "${_branch}@${_sha}")
        elseif(_sha)
            set(_tag "detached@${_sha}")
        endif()

        # Mark a modified working tree. A bench build made from uncommitted
        # changes is the case where a bare sha lies hardest: it names a commit
        # whose code is not the code that is running. Untracked files do not
        # count, because build trees and scratch files are always present and
        # would pin every build to -dirty. `git status` refreshes the index,
        # so this does not false-positive on stale stat info the way a plain
        # `git diff-index --quiet` can. Measured at 15 ms on this repo.
        if(_tag)
            execute_process(
                COMMAND "${NEREUS_GIT_EXECUTABLE}" status --porcelain --untracked-files=no
                WORKING_DIRECTORY "${NEREUS_SOURCE_DIR}"
                OUTPUT_VARIABLE _worktree_changes
                OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
            if(NOT _worktree_changes STREQUAL "")
                set(_tag "${_tag}-dirty")
            endif()
        endif()
    endif()
endif()

if(_tag MATCHES "^[ \t]*$")
    set(_tag "")
endif()

# Escape for a C string literal. Git allows a backslash-free ref name but not
# much else that matters here; escaping both is one line of insurance against
# a hand-set NEREUS_OVERRIDE breaking the compile.
set(_literal "${_tag}")
string(REPLACE "\\" "\\\\" _literal "${_literal}")
string(REPLACE "\"" "\\\"" _literal "${_literal}")

set(_content
"// Generated by cmake/LongpathBuildTag.cmake on every build. Do not edit.
// Lives in the build tree, so there is nothing here to commit.
//
// Empty on release artifacts, which are built from a tag ref.
#pragma once

#define NEREUSSDR_BUILD_TAG \"${_literal}\"
")

# Write only on change. This is what keeps the always-running build step from
# dragging a recompile behind it.
set(_existing "")
if(EXISTS "${NEREUS_OUTPUT}")
    file(READ "${NEREUS_OUTPUT}" _existing)
endif()
if(NOT _existing STREQUAL _content)
    file(WRITE "${NEREUS_OUTPUT}" "${_content}")
endif()

if(NEREUS_ANNOUNCE)
    if(_tag)
        message(STATUS "NereusSDR: smoke build, title tagged '${_tag}' (re-derived each build)")
    else()
        message(STATUS "NereusSDR: release build, title untagged")
    endif()
endif()
